// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/company/register": {
    params: {};
  };
  "/recruiter/register": {
    params: {};
  };
  "/roadmap/create": {
    params: {};
  };
  "/cv/create": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/company/register" | "/recruiter/register" | "/roadmap/create" | "/cv/create" | "/dashboard";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/companyForm.tsx": {
    id: "routes/companyForm";
    page: "/company/register";
  };
  "routes/recRegister.tsx": {
    id: "routes/recRegister";
    page: "/recruiter/register";
  };
  "routes/roadMapCreate.tsx": {
    id: "routes/roadMapCreate";
    page: "/roadmap/create";
  };
  "routes/cv.tsx": {
    id: "routes/cv";
    page: "/cv/create";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/companyForm": typeof import("./app/routes/companyForm.tsx");
  "routes/recRegister": typeof import("./app/routes/recRegister.tsx");
  "routes/roadMapCreate": typeof import("./app/routes/roadMapCreate.tsx");
  "routes/cv": typeof import("./app/routes/cv.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
};