// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/company/register": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/recruiter/register": {
    params: {};
  };
  "/roadmap/create": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/roadmap/:id": {
    params: {
      "id": string;
    };
  };
  "/application/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/myJobPostings": {
    params: {};
  };
  "/job/:id/applicants": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/company/register" | "/signup" | "/recruiter/register" | "/roadmap/create" | "/dashboard" | "/logout" | "/roadmap/:id" | "/application/:id" | "/profile" | "/myJobPostings" | "/job/:id/applicants";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/companyForm.tsx": {
    id: "routes/companyForm";
    page: "/company/register";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/recRegister.tsx": {
    id: "routes/recRegister";
    page: "/recruiter/register";
  };
  "routes/roadMapCreate.tsx": {
    id: "routes/roadMapCreate";
    page: "/roadmap/create";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/roadMapView.tsx": {
    id: "routes/roadMapView";
    page: "/roadmap/:id";
  };
  "routes/applicationForm.tsx": {
    id: "routes/applicationForm";
    page: "/application/:id";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/myJobPostings.tsx": {
    id: "routes/myJobPostings";
    page: "/myJobPostings";
  };
  "routes/jobApplicants.tsx": {
    id: "routes/jobApplicants";
    page: "/job/:id/applicants";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/companyForm": typeof import("./app/routes/companyForm.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/recRegister": typeof import("./app/routes/recRegister.tsx");
  "routes/roadMapCreate": typeof import("./app/routes/roadMapCreate.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/roadMapView": typeof import("./app/routes/roadMapView.tsx");
  "routes/applicationForm": typeof import("./app/routes/applicationForm.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/myJobPostings": typeof import("./app/routes/myJobPostings.tsx");
  "routes/jobApplicants": typeof import("./app/routes/jobApplicants.tsx");
};