<?php

namespace App\Models\User;
use App\Models\Company\Company;
use App\Models\JobPosting\JobPosting;
use App\Models\User\User;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @method static find(string $id)
 */
class Recruiter extends User
{

    protected $table = 'recruiter';

    //Only the title is fillable alongside the id since it's auto-generated by the database
    protected $fillable = ['id','title'];

    protected $primaryKey = 'id';

    public $incrementing = false;

    public $timestamps = false;
    //this shows the inheritance relationship between rec and user

    public function user() :BelongsTo
    {
        //the link between them is here
        return $this->belongsTo(User::class, 'id', 'id');
    }

    public function company():BelongsToMany
    {
        return $this->belongsToMany(Company::class,'recruiter_companies','recruiters_id','companies_id');
    }

    public function JobPosting():HasMany
    {
        return $this->HasMany(JobPosting::class,'recruiter_id');
    }
}
